const header1 = document.getElementById("name1");
const header2 = document.getElementById("name2");
const PrimaryOptic = document.getElementById("POptics");
const PrimaryBarrel = document.getElementById("PBarrel");
const PrimaryUnderbarrel = document.getElementById("PUnderbarrel");
const PrimaryOther = document.getElementById("POther");
const PrimaryAmmo = document.getElementById("PAmmo");
const PrimaryError = document.getElementById("primaryError")
const SecondaryError = document.getElementById("secondaryError")
const SecondaryOptic = document.getElementById("SOptics");
const SecondaryBarrel = document.getElementById("SBarrel");
const SecondaryOther = document.getElementById("SOther");
const SecondaryAmmo = document.getElementById("SAmmo");
const Melee=document.getElementById("Melee");
const Grenade=document.getElementById("Grenade");

//Weapons

import { Primaries,Secondaries,Melees,Grenades } from "./weapons.js";


//Optics
const IronSights=[
    "DEFAULT",
    "H&K SIGHT",
    "FULL RING SIGHT",
    "HALF RING SIGHT",
    "BACKUP SIGHT",
    "STEYR SIGHT",
    "DOUBLE OPEN SIGHT",
    "IZHMASH SIGHT",
    "SUPER SLIM SIGHT",
    "DIOPTER SIGHT",
    "BUIS SIGHT",
    "KEL-TEC SIGHT",
    "KALASHNIKOV SIGHT",
    "KAC SIGHT",
    "1200M SIGHT",
    "H&K EXPORT SIGHT",
    "HERSTAL SIGHT",
    "BUNDESWEHR SIGHT",
    "IWI SIGHT",
    "CARRY HANDLE SIGHT",
    "QUICK RELEASE SIGHT",
    "MBUS SIGHT",
    "AAC FLIP UP SIGHT",
    "DUAL APERTURE SIGHT"
]
const IronSights2=[
    "DEFAULT",
    "H&K SIGHT",
    "FULL RING SIGHT",
    "HALF RING SIGHT",
    "BACKUP SIGHT",
    "STEYR SIGHT",
    "DOUBLE OPEN SIGHT",
    "IZHMASH SIGHT",
    "SUPER SLIM SIGHT",
    "DIOPTER SIGHT",
    "BUIS SIGHT",
    "KEL-TEC SIGHT",
    "KALASHNIKOV SIGHT",
    "KAC SIGHT",
    "1200M SIGHT",
    "H&K EXPORT SIGHT",
    "HERSTAL SIGHT",
    "IWI SIGHT",
    "CARRY HANDLE SIGHT",
    "QUICK RELEASE SIGHT",
    "MBUS SIGHT",
    "AAC FLIP UP SIGHT",
    "DUAL APERTURE SIGHT"
]
//STG-44
const IronSights3=[
    "DEFAULT",
    "BACKUP SIGHT",
    "DOUBLE OPEN SIGHT",
    "SUPER SLIM SIGHT",
    "DIOPTER SIGHT",
    "BUIS SIGHT",
    "KEL-TEC SIGHT",
    "KAC SIGHT",
    "1200M SIGHT",
    "HERSTAL SIGHT",
    "IWI SIGHT",
    "CARRY HANDLE SIGHT",
    "QUICK RELEASE SIGHT",
    "MBUS SIGHT",
    "AAC FLIP UP SIGHT",
    "DUAL APERTURE SIGHT"
]
const RedDots=[
    "Z-POINT",
    "EOTECH XPS2",
    "DELTA SIGHT",
    "MARS",
    "EOTECH 552",
    "MINI SIGHT",
    "COMP AIMPOINT",
    "PKA-S",
    "REFLEX SIGHT",
    "KOBRA SIGHT",
    "COYOTE SIGHT",
    "MICRODOT MINI",
    "PILAD 3",
    "KOBRA EKP SIGHT",
    "ACRO P-1 SIGHT",
    "BARKSA ELECTRO SIGHT",
    "EOTECH M40",
    "KOUSAKU SIGHT",
    "MICRODOT SRS",
    "OKP-7",
    "UH-1 SIGHT",
    "DDHB REFLEX",
    "DCL 120",
    "KOUSAKU OLED SIGHT"
]
const Scopes=[
    "C79",
    "PK-A",
    "M145",
    "MALCOLM 3X SCOPE",
    "PSO-1 SCOPE",
    "TA44 ACOG",
    "ACOG SCOPE",
    "VCOG 6X SCOPE",
    "TA33 ACOG",
    "HENSOLDT 3X SIGHT",
    "HENSOLDT Z24",
    "SWAROVSKI SCOPE",
    "TA11 ACOG",
    "PU-1 SCOPE",
    "FF-3X NV",
    "PSO-1M2 SCOPE",
    "TA01 ACOG",
    "ELECTRA SX",
    "REFLECTOR SCOPE",
    "VCOG 8X SCOPE",
    "SUSAT SCOPE",
    "GLOBAL OFFENSIVE"
]
//M14
const Scopes2=[
    "C79",
    "PK-A",
    "M145",
    "MALCOLM 3X SCOPE",
    "PSO-1 SCOPE",
    "TA44 ACOG",
    "ACOG SCOPE",
    "VCOG 6X SCOPE",
    "TA33 ACOG",
    "HENSOLDT 3X SIGHT",
    "HENSOLDT Z24",
    "SWAROVSKI SCOPE",
    "TA11 ACOG",
    "PU-1 SCOPE",
    "FF-3X NV",
    "PSO-1M2 SCOPE",
    "TA01 ACOG",
    "ELECTRA SX",
    "REFLECTOR SCOPE",
    "VCOG 8X SCOPE",
    "SUSAT SCOPE",
    "GLOBAL OFFENSIVE"
]
//SNIPERS
const Scopes3=[
    "C79",
    "PK-A",
    "M145",
    "MALCOLM 3X SCOPE",
    "TA44 ACOG",
    "ACOG SCOPE",
    "VCOG 6X SCOPE",
    "TA33 ACOG",
    "HENSOLDT 3X SIGHT",
    "HENSOLDT Z24",
    "TA11 ACOG",
    "PU-1 SCOPE",
    "FF-3X NV",
    "TA01 ACOG",
    "ELECTRA SX",
    "REFLECTOR SCOPE",
    "VCOG 8X SCOPE",
    "SUSAT SCOPE",
    "GLOBAL OFFENSIVE",
    "LEUPOLD M8-2X",
    "SAGITARIUS 40X",
    "PM II",
    "LEUPOLD MARK 4",
    "SIDEWINDER ED",
    "NXS 8-32",
    "KOM 10X42",
    "HI-POWER 8-32",
    "LEUPOLD M8-6X",
    "KLASSIK LM",
    "NXS 5.5-22"
]
const Scopes4=[
    "C79",
    "PK-A",
    "M145",
    "TA44 ACOG",
    "ACOG SCOPE",
    "VCOG 6X SCOPE",
    "TA33 ACOG",
    "HENSOLDT 3X SIGHT",
    "TA11 ACOG",
    "TA01 ACOG"
]
const SpecialSights=[
    "OEG",
    "MAGLITE",
    "AMT-TERMINATOR",
    "HANDMADE SIGHT",
    "PLAGUE INSIGHT",
    "ANIMU SIGHT",
    "FURRO SIGHT",
    "👌👍",
    "ANTI SIGHT"
]
const SpecialSights2=[
    "MAGLITE",
    "AMT-TERMINATOR",
    "HANDMADE SIGHT",
    "PLAGUE INSIGHT",
    "ANIMU SIGHT",
    "FURRO SIGHT",
    "👌👍",
    "ANTI SIGHT"
]
const POptics={
    "DEFAULT":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    //ARs
    "AK12":[...IronSights,...RedDots,...Scopes,...SpecialSights],
    "AN-94":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "AS VAL":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "SCAR-L":[...IronSights,...RedDots,...Scopes,...SpecialSights,"PM II"],
    "AUG A1":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "M16A4":[...IronSights,...RedDots,...Scopes,...SpecialSights],
    "G36":[...IronSights,...RedDots,...Scopes,...SpecialSights,"HENSOLDT DUAL OPTIC"],
    "M16A1":[...IronSights2,...RedDots,...Scopes,...SpecialSights,"COLT RETRO SCOPE"],
    "M16A3":[...IronSights,...RedDots,...Scopes,...SpecialSights],
    "TYPE 20":[...IronSights,...RedDots,...Scopes,...SpecialSights,"REMOVE IRONS","PM II"],
    "AUG A2":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "K2":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "FAMAS F1":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "AK47":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "AUG A3":[...IronSights,...RedDots,...Scopes,...SpecialSights],
    "L85A2":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "HK416":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "AK74":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "AKM":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "AK103":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "TAR-21":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "TYPE-88":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "M231":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "C7A2":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "STG-44":[...IronSights3,...RedDots,...Scopes,...SpecialSights],
    "G11K2":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "M14":[...RedDots,...Scopes2,"CARRY HANDLE SIGHT","OEG","MAGLITE","AMT-TERMINATOR","HANDMADE SIGHT","PLAGUE INSIGHT"],
    "BEOWULF ECR":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "SCAR-H":[...IronSights,...RedDots,...Scopes,...SpecialSights,"PM II"],
    "AK12BR":[...IronSights,...RedDots,...Scopes,...SpecialSights],
    "G3A3":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "AG-3":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "HK417":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "HENRY 45-70":[...IronSights2,...RedDots,...Scopes,...SpecialSights,'MALCOLM 6X SCOPE'],
    "FAL 50.00":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    //Carbines
    "M4A1":[...IronSights,...RedDots,...Scopes,...SpecialSights],
    "G36K":[...IronSights,...RedDots,...Scopes,...SpecialSights],
    "M4":[...IronSights,...RedDots,...Scopes,...SpecialSights],
    "L22":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "SCAR PDW":[...IronSights,...RedDots,...Scopes,...SpecialSights,"PM II"],
    "AKU12":[...IronSights,...RedDots,...Scopes,...SpecialSights],
    "GROZA-1":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "OTS-126":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "AK12C":[...IronSights,...RedDots,...Scopes,...SpecialSights],
    "HONEY BADGER":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "K1A":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "SR-3M":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "GROZA-4":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "MC51":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "FAL 50.63 PARA":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "1858 CARBINE":[...IronSights2,...RedDots,...Scopes,...SpecialSights,"LEUPOLD M8-2X"],
    "AK105":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "JURY":[...IronSights2,...RedDots,...Scopes,...SpecialSights,"LEUPOLD M8-2X"],
    "KAC SSR":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "GRYOJET CARBINE":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "C8A2":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "X95R":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "HK51B":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "CAN CANNON":[...IronSights2,...RedDots,...Scopes,...SpecialSights,"PM II"],
    //Shotguns
    "KSG 12":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "MODEL 870":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "DBV12":[...IronSights,...RedDots,...Scopes,...SpecialSights],
    "KS-23M":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "SAIGA-12":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "STEVENDS DB":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "E-GUN":[...RedDots,...Scopes,"OEG","HANDMADE SIGHT","PLAGEUE INSIGHT"],
    "AA-12":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "SPAS-12":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "DT11":[...IronSights2,...RedDots,...Scopes,...SpecialSights,"OLYMPIAN TARGET","SIEGE SIGHT"],
    "USAS-12":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    //PDW
    "MP5K":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "UMP45":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "G36C":[...IronSights2,...RedDots,...Scopes,...SpecialSights,"HENSOLDT DUAL OPTIC"],
    "MP7":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "MAC10":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "P90":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "COLT MARS":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "MP5":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "COLT SMG 633":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "L2A3":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "MP5SD":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "MP10":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "M3A1":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "MP5/10":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "UZI":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "AUG A3 PARA XS":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "K7":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "AKS74U":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "PPSH-41":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "FAL PARA SHORTY":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "KRISS VECTOR":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "PP-19 BIZON":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "MP40":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "X95 SMG":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "TOMMY GUN":[...IronSights2,...RedDots,...Scopes,...SpecialSights,"LYMAN SIGHT"],
    "RAMA 1130":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "BWC9 A":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "FIVE-0":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    //DMRs
    "MK11":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "SKS":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "SL-8":[...IronSights,...RedDots,...Scopes,...SpecialSights,"HENSOLDT DUAL OPTICS"],
    "VSS VINTOREZ":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "MSG90":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "M21":["CARRY HANDLE SIGHT",...RedDots,...Scopes,"OEG","MAGLITE","AMT-TERMINATOR","HANDMADE SIGHT","PLAGUE INSIGHT"],
    "BEOWULF TCR":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "SA58 SPR":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "SCAR SSR":[...IronSights2,...RedDots,...Scopes,...SpecialSights,"PM II"],
    //LMGs
    "COLT LMG":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "M60":[...IronSights2,...RedDots,...Scopes,...SpecialSights,"ANTI-AIRCRAFT IRONS"],
    "AUG HBAR":[...IronSights,...RedDots,...Scopes,...SpecialSights],
    "MG36":[...IronSights,...RedDots,...Scopes,...SpecialSights],
    "RPK12":[...IronSights,...RedDots,...Scopes,...SpecialSights],
    "L86 LSW":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "RPK":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "HK21E":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "HAMR IAR":[...IronSights,...RedDots,...Scopes,...SpecialSights,"PM II"],
    "RPK74":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "MG3KWS":[...IronSights2,...RedDots,...Scopes,...SpecialSights,"ANTI-AIRCRAFT IRONS"],
    "MGV-176":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "STONER 96":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "MG42":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    //Sniper rifles
    "INTERVENTION":[...IronSights2,...RedDots,...Scopes3,...SpecialSights],
    "MODEL 700":[...IronSights2,...RedDots,...Scopes3,...SpecialSights],
    "DRAGUNOV SVU":[...IronSights2,...RedDots,...Scopes3,...SpecialSights],
    "AWS":[...IronSights2,...RedDots,...Scopes3,...SpecialSights],
    "BFG 50":[...IronSights2,...RedDots,...Scopes3,...SpecialSights],
    "AWM":[...IronSights2,...RedDots,...Scopes3,...SpecialSights],
    "TRG-42":[...IronSights2,...RedDots,...Scopes3,...SpecialSights],
    "MOSIN NAGANT":[...IronSights2,...RedDots,...Scopes3,...SpecialSights],
    "DRAGUNOV SVDS":[...IronSights2,...RedDots,...Scopes3,...SpecialSights],
    "M1903":[...IronSights2,...RedDots,...Scopes3,...SpecialSights,"UNERTL 8X SCOPE"],
    "K14":[...IronSights2,...RedDots,...Scopes3,...SpecialSights],
    "HECATE II":[...IronSights2,...RedDots,...Scopes3,...SpecialSights],
    "FT300":[...IronSights2,...RedDots,...Scopes3,...SpecialSights,"OLYMPIAN TARGET"],
    "M107":[...IronSights2,...RedDots,...Scopes3,...SpecialSights],
    "STERY SCOUT":[...IronSights2,...RedDots,...Scopes3,...SpecialSights],
    "WA2000":[...IronSights2,...RedDots,...Scopes3,...SpecialSights],
    "NTW-20":[...RedDots,...Scopes3,...SpecialSights]
}

const SOptics={
    "DEFAULT":[...IronSights,...RedDots,...Scopes,...SpecialSights],
    "G17":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "M9":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "M1911A1":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "DESERT EAGLE L5":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "G21":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "G23":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "M45A1":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "G40":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "KG-99":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "G50":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "FIVE SEVEN":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "ZIP 22":[...IronSights2,...RedDots,...Scopes4,...SpecialSights,"PSO-1 SCOPE","PSO-1M2 SCOPE","PM II","SWAROVSKI SCOPE","SAGITTARIUS 40X"],
    "GI M1":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "HARDBALLER":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "IZHEVSK PB":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "MAKAROV PM":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "GB-22":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "DESERT EAGLE XIX":[...IronSights2,...RedDots,...Scopes4,...SpecialSights,"LEUPOLD M8-6X"],
    "AUTOMAG III":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "GYROJET MARK I":[...IronSights2,...RedDots,...Scopes4,...SpecialSights,"LEUPOLD M8-6X"],
    "GSP":["DEFAULT",...RedDots,...Scopes4,"MAGLITE","AMT-TERMINATOR",'PLAGUE INSIGHT'],
    "GRIZZLY":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "M2011":[...IronSights2,...RedDots,...Scopes4,...SpecialSights,"OLYMPIAN TARGET"],
    "ALIEN":[...IronSights2,...RedDots,...Scopes4,...SpecialSights,"OLYMPIAN TARGET"],
    "AF2011-A1":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    //Machine Pistols
    "G18C":[...IronSights2,...RedDots,...Scopes4,...SpecialSights2],
    "93R":[...IronSights2,...RedDots,...Scopes4,...SpecialSights2],
    "PP-2000":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "TEC-9":[...IronSights2,...RedDots,...Scopes4,...SpecialSights2],
    "MICRO UZI":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "ŠKORPION VZ.61":["DEFAULT",...RedDots,"C79","PK-A","M145","TA44 ACOG","ACOG SCOPE","TA01 ACOG","MAGLITE","AMT-TERMIANTOR","PLAGUE INSIGHT"],
    "ASMI":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "MP1911":[...IronSights2,...RedDots,...Scopes4,...SpecialSights2],
    "ARM PISTOL":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    //Revolvers
    "MP412 REX":[...IronSights2,...RedDots,...Scopes4,...SpecialSights2,"LEUPOLD M8-2X","PSO-1 SCOPE","SWAROVSKI SCOPE","PU-1 SCOPE","PSO-1M2 SCOPE"],
    "MATEBA 6":[...IronSights2,...RedDots,...Scopes4,...SpecialSights2,"LEUPOLD M8-2X","PU-1 SCOPE","LEUPOLD M8-6X"],
    "1858 NEW ARMY":[...IronSights2,...RedDots,...Scopes4,...SpecialSights2,"LEUPOLD M8-2X","PU-1 SCOPE","LEUPOLD M8-6X"],
    "REDHAWK 44":[...IronSights2,...RedDots,...Scopes4,...SpecialSights2,"LEUPOLD M8-2X","PU-1 SCOPE","LEUPOLD M8-6X"],
    "JUDGE":[...IronSights2,...RedDots,...Scopes4,...SpecialSights2,"LEUPOLD M8-2X","PU-1 SCOPE","LEUPOLD M8-6X"],
    "EXECUTIONER":[...IronSights2,...RedDots,...Scopes4,...SpecialSights2,"LEUPOLD M8-2X","PU-1 SCOPE","LEUPOLD M8-6X"],
    //Other
    "SUPER SHORTY":[...IronSights2,...RedDots,...Scopes4,...SpecialSights,"PM II"],
    "SFG 50":[...IronSights2,...RedDots,...Scopes3,...SpecialSights],
    "M79 THUMPER":[...IronSights2,...RedDots,...Scopes,...SpecialSights,"UNFOLDED LEAF SIGHT"],
    "ADVANCED COILGUN":[...RedDots,...Scopes4,..."OEG","HANDMADE SIGHT","PLAGUE SIGHT"],
    "SAWED OFF":[...IronSights2,...RedDots,...Scopes,...SpecialSights],
    "SAIGA-12U":[...IronSights2,...RedDots,...Scopes4,...SpecialSights],
    "OBREZ":[...IronSights2,...RedDots,...Scopes3,...SpecialSights],
    "SASS 308":[...IronSights2,...RedDots,...Scopes4,...SpecialSights2]
    }
//Barrels
const Barrels=[
    "CARBINE BARREL",
    "BARS BARREL"
]
const Muzzles=[
    "DEFAULT",
    "FLASH HIDER",
    "COMPENSATOR",
    "MUZZLE BREAK",
    "T-BRAKE",
    "X-RING",
    "HALBEK DEVICE",
    "LOUDENER",
    "MUZZLE BOOSTER"
]
const Suppressors=[
    "SUPPRESSOR",
    "R2 SUPPRESSOR",
    "ARS SUPPRESSOR",
    "PBS-1 SUPPRESSOR",
    "PBS-4 SUPPRESSOR",
    "MUFFLER",
    "OIL FILTER",
]
//HENRY 410
const Suppressors2=[
    "SUPPRESSOR",
    "R2 SUPPRESSOR",
    "ARS SUPPRESSOR",
    "PBS-1 SUPPRESSOR",
    "PBS-4 SUPPRESSOR",
    "MUFFLER",
]
const Suppressors3=[
    "SUPPRESSOR",
    "R2 SUPPRESSOR",
    "ARS SUPPRESSOR",
    "PBS-1 SUPPRESSOR",
    "PBS-4 SUPPRESSOR",
    "MUFFLER",
    "OIL FILTER",
    "OSPREY SUPPRESSOR"
]
const PBarrels={
    "DEFAULT":[...Muzzles,...Suppressors],
    //ARs
    "AK12":[...Barrels,...Muzzles,...Suppressors],
    "AN-94":[...Muzzles,...Suppressors],
    "AS VAL":["DEFAULT","SUPPRESSOR..?"],
    "SCAR-L":[...Muzzles,...Suppressors,"CARBINE BARREL","SQUAD BARREL"],
    "AUG A1":["CARBINE BARREL",...Muzzles,...Suppressors],
    "M16A4":["CARBINE BARREL",...Muzzles,...Suppressors],
    "G36":[...Muzzles,...Suppressors],
    "M16A1":[...Muzzles,...Suppressors],
    "M16A3":["CARBINE BARREL",...Muzzles,...Suppressors],
    "TYPE 20":[...Muzzles,...Suppressors,"CARBINE BARREL","SQUAD BARREL","INTEGRAL SUPPRESSOR"],
    "AUG A2":["CARBINE BARREL",...Muzzles,...Suppressors],
    "K2":[...Muzzles,...Suppressors,"CARBINE BARREL","SQUAD BARREL"],
    "FAMAS F1":[...Muzzles,...Suppressors,"CARBINE BARREL","SQUAD BARREL"],
    "AK47":["CARBINE BARREL",...Muzzles,...Suppressors],
    "AUG A3":["CARBINE BARREL",...Muzzles,...Suppressors],
    "L85A2":["CARBINE BARREL",...Muzzles,...Suppressors],
    "HK416":[...Muzzles,...Suppressors,"CARBINE BARREL","SQUAD BARREL"],
    "AK74":["CARBINE BARREL",...Muzzles,...Suppressors],
    "AKM":["CARBINE BARREL",...Muzzles,...Suppressors],
    "AK103":[...Barrels,...Muzzles,...Suppressors,"SQUAD BARREL"],
    "TAR-21":["CTAR BARREL",...Muzzles,...Suppressors],
    "TYPE-88":[...Muzzles,...Suppressors,"CARBINE BARREL","SQUAD BARREL"],
    "M231":["CARBINE BARREL",...Muzzles,...Suppressors],
    "C7A2":["CARBINE BARREL",...Muzzles,...Suppressors,"LSW BARREL"],
    "STG-44":[...Muzzles,...Suppressors],
    "G11K2":[...Muzzles,...Suppressors],
    "M14":[...Muzzles,...Suppressors],
    "BEOWULF ECR":[...Muzzles,...Suppressors],
    "SCAR-H":[...Muzzles,...Suppressors],
    "AK12BR":[...Muzzles,...Suppressors],
    "G3A3":[...Muzzles,...Suppressors],
    "AG-3":[...Muzzles,...Suppressors],
    "HK417":[...Muzzles,...Suppressors,"SHORT BARREL","SQUAD BARREL"],
    "HENRY 45-70":[...Muzzles,...Suppressors2],
    "FAL 50.00":[...Muzzles,...Suppressors],
    //Carbines
    "M4A1":[...Muzzles,...Suppressors,"CARBINE BARREL"],
    "G36K":[...Muzzles,...Suppressors,"SQUAD BARREL"],
    "M4":[...Muzzles,...Suppressors,"CARBINE BARREL"],
    "L22":[...Muzzles,...Suppressors,"SQUAD BARREL"],
    "SCAR PDW":[...Muzzles,...Suppressors,"SQUAD BARREL"],
    "AKU12":[...Muzzles,...Suppressors,"SQUAD BARREL","CARBINE BARREL"],
    "GROZA-1":[...Muzzles,...Suppressors],
    "OTS-126":[...Muzzles,...Suppressors,"SHORT BARREL"],
    "AK12C":[...Muzzles,...Suppressors,"CARBINE BARREL","SQUAD BARREL"],
    "HONEY BADGER":[...Muzzles,...Suppressors,"SQUAD BARREL","REMOVE SUPPRESSOR"],
    "K1A":[...Muzzles,...Suppressors],
    "SR-3M":[...Muzzles,...Suppressors,"VIKHR SUPPRESSOR"],
    "GROZA-4":["DEFAULT"],
    "MC51":[...Muzzles,...Suppressors,"INTEGRAL SUPPRESSOR"],
    "FAL 50.63 PARA":[...Muzzles,...Suppressors],
    "1858 CARBINE":[...Muzzles,"SHORT BARREL","LONG BARREL"],
    "AK105":[...Muzzles,...Suppressors,"SQUAD ABRREL","CARBINE BARREL","BARS BARREL"],
    "JURY":[...Muzzles],
    "KAC SSR":["DEFAULT"],
    "GRYOJET CARBINE":["DEFAULT"],
    "C8A2":[...Muzzles,...Suppressors,"CARBINE BARREL"],
    "X95R":[...Muzzles,...Suppressors],
    "HK51B":[...Muzzles,...Suppressors,"SQUAD BARREL","SHORT BARREL"],
    "CAN CANNON":["DEFAULT","HEAVY CAN","GOLF BALL","CANNON BALL","TENNIS BALLS","BLOXY COLA"],
    //Shotguns
    "KSG 12":[...Muzzles,...Suppressors,"IMPROVED CHOKE","DUCKBILL CHOKE","MODIFIED CHOKE","PARADOX CHOKE","KSG 25 BARREL"],
    "MODEL 870":[...Muzzles,...Suppressors,"FULL CHOKE","IMPROVED CHOKE","DUCKBILL CHOKE","MODIFIED CHOKE","DIVERTER"],
    "DBV12":[...Muzzles,...Suppressors,"IMPROVED CHOKE","DUCKBILL CHOKE","PARADOX CHOKE"],
    "KS-23M":[...Muzzles,...Suppressors,"SPORTING BARREL","PARADOX CHOKE"],
    "SAIGA-12":[...Muzzles,...Suppressors,"IMPROVED CHOKE","DUCKBILL CHOKE",'MODIFIED CHOKE'],
    "STEVENDS DB":[...Muzzles,"MUFFLER","FULL CHOKE","IMPROVED CHOKE","DUCKBILL CHOKE","MODIFIED CHOKE","PARADOX CHOKE"],
    "E-GUN":["DEFAULT"],
    "AA-12":["SPORTING BARREL",...Muzzles,...Suppressors,"IMPROVED CHOKE","DUCKBILL CHOKE",'PARADOX CHOKE'],
    "SPAS-12":[...Muzzles,...Suppressors,"IMPROVED CHOKE","DUCKBILL CHOKE","MODIFIED CHOKE"],
    "DT11":[...Muzzles,"INTEGRAL SUPPRESSOR","COMBAT BARREL",'SAWED OFF BARREL',"FULL CHOKE","IMPROVED CHOKE","DUCKBILL CHOKE","MODIFIED CHOKE","PARADOX CHOKE"],
    "USAS-12":[...Muzzles,...Suppressors,"IMPROVED CHOKE","MODIFIED CHOKE","PARADOX CHOKE"],
    //PDW
    "MP5K":[...Muzzles,...Suppressors,"LONG BARREL","OSPREY SUPPRESSOR"],
    "UMP45":[...Muzzles,...Suppressors,"LONG BARREL","OSPREY SUPPRESSOR"],
    "G36C":[...Muzzles,...Suppressors,"SQUAD BARREL"],
    "MP7":[...Muzzles,...Suppressors,"OSPREY SUPPRESSOR"],
    "MAC10":[...Muzzles,...Suppressors,"LONG BARREL","SQUAD BARREL","OSPREY SUPPRESSOR"],
    "P90":[...Muzzles,...Suppressors,"LONG BARREL","OSPREY SUPPRESSOR"],
    "COLT MARS":[...Muzzles,...Suppressors,"SQUAD BARREL"],
    "MP5":[...Muzzles,...Suppressors,"LONG BARREL","OSPREY SUPPRESSOR"],
    "COLT SMG 633":[...Muzzles,...Suppressors,"LONG BARREL","OSPREY SUPPRESSOR"],
    "L2A3":[...Muzzles,...Suppressors,"SHORT BARREL","LONG BARREL","OSPREY SUPPRESSOR"],
    "MP5SD":["DEFAULT","LONG BARREL"],
    "MP10":[...Muzzles,...Suppressors,"LONG BARREL","OSPREY SUPPRESSOR"],
    "M3A1":[...Muzzles,...Suppressors,"OSPREY SUPPRESSOR"],
    "MP5/10":[...Muzzles,...Suppressors,"LONG BARREL","OSPREY SUPPRESSOR"],
    "UZI":[...Muzzles,...Suppressors,"LONG BARREL","OSPREY SUPPRESSOR"],
    "AUG A3 PARA XS":[...Muzzles,...Suppressors,"LONG BARREL","OSPREY SUPPRESSOR"],
    "K7":["DEFAULT"],
    "AKS74U":[...Muzzles,...Suppressors,"SQUAD BARREL"],
    "PPSH-41":[...Muzzles,...Suppressors,"LONG BARREL","OBREZ BARREL","OSPREY SUPPRESSOR"],
    "FAL PARA SHORTY":[...Muzzles,...Suppressors],
    "KRISS VECTOR":[...Muzzles,...Suppressors,"LONG BARREL","OSPREY SUPPRESSOR"],
    "PP-19 BIZON":[...Muzzles,...Suppressors,"OSPREY SUPPRESSOR"],
    "MP40":[...Muzzles,...Suppressors,"OSPREY SUPPRESSOR"],
    "X95 SMG":[...Muzzles,...Suppressors,"OSPREY SUPPRESSOR"],
    "TOMMY GUN":[...Muzzles,...Suppressors,"SQUAD BARREL","OSPREY SUPPRESSOR"],
    "RAMA 1130":[...Muzzles,...Suppressors,"LONG BARREL","OSPREY SUPPRESSOR"],
    "BWC9 A":[...Muzzles,...Suppressors,"SHORT BARREL","OSPREY SUPPRESSOR"],
    "FIVE-0":[...Muzzles,...Suppressors],
    //DMRs
    "MK11":[...Muzzles,...Suppressors,"ASSAULT BARREL"],
    "SKS":[...Muzzles,...Suppressors,"ASSAULT BARREL"],
    "SL-8":[...Muzzles,...Suppressors,"MARKSMAN BARREL"],
    "VSS VINTOREZ":["DEFAULT","SUPPRESSOR..?"],
    "MSG90":[...Muzzles,...Suppressors],
    "M21":[...Muzzles,...Suppressors],
    "BEOWULF TCR":[...Muzzles,...Suppressors,"CARBINE BARREL","SQUAD BARREL"],
    "SA58 SPR":[...Muzzles,...Suppressors],
    "SCAR SSR":[...Muzzles,...Suppressors,"SHORT BARREL"],
    //LMGs
    "COLT LMG":[...Muzzles,...Suppressors,"CARBINE BARREL"],
    "M60":[...Muzzles,...Suppressors],
    "AUG HBAR":[...Muzzles,...Suppressors],
    "MG36":[...Muzzles,...Suppressors],
    "RPK12":[...Muzzles,...Suppressors,"CARBINE BARREL"],
    "L86 LSW":[...Muzzles,...Suppressors,"CARBINE BARREL"],
    "RPK":[...Muzzles,...Suppressors],
    "HK21E":[...Muzzles,...Suppressors],
    "HAMR IAR":[...Muzzles,...Suppressors,"CARBINE BARREL","SQUAD BARREL"],
    "RPK74":[...Muzzles,...Suppressors],
    "MG3KWS":[...Muzzles,...Suppressors],
    "MGV-176":[...Muzzles,...Suppressors,"SHORT BARREL"],
    "STONER 96":[...Muzzles,...Suppressors],
    "MG42":[...Muzzles,...Suppressors],
    //Sniper rifles
    "INTERVENTION":[...Muzzles,...Suppressors,"CQB BARREL"],
    "MODEL 700":[...Muzzles,...Suppressors,"LIGHT BARREL","HEAVY BARREL"],
    "DRAGUNOV SVU":[...Muzzles,...Suppressors],
    "AWS":["DEFAULT"],
    "BFG 50":[...Muzzles,...Suppressors,"LIGHT BARREL","HEAVY BARREL","CARBINE BARREL"],
    "AWM":[...Muzzles,...Suppressors],
    "TRG-42":[...Muzzles,...Suppressors,"LIGHT BARREL","HEAVY BARREL"],
    "MOSIN NAGANT":[...Muzzles,...Suppressors,"LIGHT BARREL","FRONT POST"],
    "DRAGUNOV SVDS":[...Muzzles,...Suppressors,"LIGHT BARREL"],
    "M1903":[...Muzzles,...Suppressors,"LIGHT BARREL","AIR SERVICE BARREL"],
    "K14":[...Muzzles,...Suppressors,"LIGHT BARREL"],
    "HECATE II":[...Muzzles,...Suppressors,"LIGHT BARREL","HEAVY BARREL","CQB BARREL"],
    "FT300":[...Muzzles,...Suppressors,"LIGHT BARREL","HEAVY BARREL"],
    "M107":[...Muzzles,...Suppressors,"CQB BARREL"],
    "STERY SCOUT":[...Muzzles,...Suppressors,"LIGHT BARREL","HEAVY BARREL"],
    "WA2000":[...Muzzles,...Suppressors],
    "NTW-20":[...Muzzles,"OBREZ BARREL","HEAVY BARREL"]

}
const SBarrels={
    "DEFAULT":[...Muzzles,...Suppressors],
    "G17":[...Muzzles,...Suppressors3,"LONG BARREL"],
    "M9":[...Muzzles,...Suppressors3,"LONG BARREL"],
    "M1911A1":[...Muzzles,...Suppressors3],
    "DESERT EAGLE L5":[...Muzzles,...Suppressors,"EXTENDED BARREL"],
    "G21":[...Muzzles,...Suppressors3,"LONG BARREL"],
    "G23":[...Muzzles,...Suppressors3,"LONG BARREL"],
    "M45A1":[...Muzzles,...Suppressors3],
    "G40":[...Muzzles,...Suppressors3,"SHORT BARREL"],
    "KG-99":[...Muzzles,...Suppressors3,"LONG BARREL"],
    "G50":[...Muzzles,...Suppressors3,"HEAVY BARREL"],
    "FIVE SEVEN":[...Muzzles,...Suppressors3],
    "ZIP 22":[...Muzzles,...Suppressors3],
    "GI M1":[...Muzzles,...Suppressors3,"HEAVY BARREL"],
    "HARDBALLER":[...Muzzles,...Suppressors3,"SHORT BARREL"],
    "IZHEVSK PB":["DEFAULT"],
    "MAKAROV PM":[...Muzzles,...Suppressors3,"LONG BARREL"],
    "GB-22":[...Muzzles,...Suppressors3,"CUT DOWN BARREL","SPORTING BARREL"],
    "DESERT EAGLE XIX":[...Muzzles,...Suppressors,"EXTENDED BARREL","POLICE BARREL"],
    "AUTOMAG III":[...Muzzles,...Suppressors],
    "GYROJET MARK I":["DEFAULT","SHORT BARREL","LONG BARREL"],
    "GSP":[...Muzzles,...Suppressors3,"TARGET WEIGHT"],
    "GRIZZLY":[...Muzzles,...Suppressors3,"HEAVY BARREL"],
    "M2011":[...Muzzles,...Suppressors3,"LONG BARREL"],
    "ALIEN":[...Muzzles,...Suppressors3],
    "AF2011-A1":[...Muzzles,...Suppressors3],
    //Machine Pistols
    "G18C":[...Muzzles,...Suppressors3,"LONG BARREL"],
    "93R":[...Muzzles,...Suppressors3],
    "PP-2000":[...Muzzles,...Suppressors3],
    "TEC-9":[...Muzzles,...Suppressors3,"LONG BARREL","SHORT BARREL"],
    "MICRO UZI":[...Muzzles,...Suppressors3],
    "ŠKORPION VZ.61":[...Muzzles,...Suppressors3,"LONG BARREL"],
    "ASMI":[...Muzzles,...Suppressors3],
    "MP1911":[...Muzzles,...Suppressors3,"SHORT BARREL"],
    "ARM PISTOL":[...Muzzles,...Suppressors],
    //Revolvers
    "MP412 REX":[...Muzzles,"SNUBNOSE","COWBOY BARREL"],
    "MATEBA 6":[...Muzzles,"SNUBNOSE","COWBOY BARREL"],
    "1858 NEW ARMY":[...Muzzles,"SNUBNOSE","COWBOY BARREL"],
    "REDHAWK 44":[...Muzzles,"SNUBNOSE","COWBOY BARREL"],
    "JUDGE":[...Muzzles,"TAURUS BARREL"],
    "EXECUTIONER":[...Muzzles,"TAURUS BARREL"],
    //Other
    "SUPER SHORTY":[...Muzzles,...Suppressors,"FULL CHOKE","IMPROVED CHOKE","DUCKBILL CHOKE","MODIFIED CHOKE","PARADOX CHOKE","DIVERTER"],
    "SFG 50":[...Muzzles,...Suppressors],
    "M79 THUMPER":["COMPENSATOR","DEFAULT","MUZZLE BREKE","T-BRAKE","X-RING","LOUDENER","CUT DOWN BARREL"],
    "ADVANCED COILGUN":["DEFAULT"],
    "SAWED OFF":[...Muzzles,"MUFFLER","FULL CHOKE","IMPROVED CHOKE","DUCKBILL CHOKE","MODIFIED CHOKE","PARADOX CHOKE","DIVERTER"],
    "SAIGA-12U":[...Muzzles,...Suppressors,"IMPROVED CHOKE","DUCKBILL CHOKE","MODIFIED CHOKE","PARADOX CHOKE","DIVERTER"],
    "OBREZ":[...Muzzles,...Suppressors,"FRONT POST","LONG BARREL"],
    "SASS 308":[...Muzzles,...Suppressors,"LIGHT BARREL"]
}
//Underbarrels
const Accessories=[
    "DEFAULT",
    "FLASHLIGHT",
    "RED LASER",
    "GREEN LASER",
    "BLUE LASER",
    "YELLOW LASER",
    "TRI LASER"
]
const Grips=[
    "VERTICAL GRIP",
    "ANGLED GRIP",
    "POTATO GRIP",
    "SKELETON GRIP",
    "FOLDING GRIP",
    "STUBBY GRIP",
    "PISTOL GRIP",
    "SIDEWAYS GRIP",
    "CHAINSAW GRIP"
]
const Grips2=[
    "VERTICAL GRIP",
    "ANGLED GRIP",
    "POTATO GRIP",
    "SKELETON GRIP",
    "FOLDING GRIP",
    "STUBBY GRIP",
    "PISTOL GRIP",
    "SIDEWAYS GRIP",
    "CHAINSAW GRIP",
    "ROMANIAN GRIP"
]
const PUnderbarrels={
    "DEFAULT":[...Accessories,...Grips],
     //ARs
    "AK12":[...Accessories,...Grips],
    "AN-94":[...Accessories,...Grips2],
    "AS VAL":[...Accessories,...Grips],
    "SCAR-L":[...Accessories,...Grips],
    "AUG A1":[...Accessories,...Grips],
    "M16A4":[...Accessories,...Grips],
    "G36":[...Accessories,...Grips2],
    "M16A1":[...Accessories,...Grips],
    "M16A3":[...Accessories,...Grips],
    "TYPE 20":[...Accessories,...Grips],
    "AUG A2":[...Accessories,...Grips],
    "K2":[...Accessories,...Grips],
    "FAMAS F1":[...Accessories,...Grips],
    "AK47":[...Accessories,...Grips2],
    "AUG A3":[...Accessories,...Grips],
    "L85A2":[...Accessories,...Grips],
    "HK416":[...Accessories,...Grips],
    "AK74":[...Accessories,...Grips2],
    "AKM":[...Accessories,...Grips2],
    "AK103":[...Accessories,...Grips2],
    "TAR-21":[...Accessories,...Grips],
    "TYPE-88":[...Accessories,...Grips2],
    "M231":[...Accessories,...Grips],
    "C7A2":[...Accessories,...Grips],
    "STG-44":[...Accessories,...Grips],
    "G11K2":[...Accessories,...Grips2],
    //BRs
    "M14":[...Accessories,...Grips2],
    "BEOWULF ECR":[...Accessories,...Grips2],
    "SCAR-H":[...Accessories,...Grips],
    "AK12BR":[...Accessories,...Grips],
    "G3A3":[...Accessories,...Grips],
    "AG-3":[...Accessories,...Grips],
    "HK417":[...Accessories,...Grips],
    "HENRY 45-70":[...Accessories,...Grips],
    "FAL 50.00":[...Accessories,...Grips2],
    //Carbines
    "M4A1":[...Accessories,...Grips,"HERA CQR GRIP"],
    "G36K":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "M4":[...Accessories,...Grips,"HERA CQR GRIP"],
    "L22":[...Accessories,...Grips],
    "SCAR PDW":[...Accessories,...Grips],
    "AKU12":[...Accessories,...Grips,"HERA CQR GRIP"],
    "GROZA-1":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "OTS-126":[...Accessories,...Grips,"HERA CQR GRIP"],
    "AK12C":[...Accessories,...Grips,"HERA CQR GRIP"],
    "HONEY BADGER":[...Accessories,...Grips,"HERA CQR GRIP"],
    "K1A":[...Accessories,...Grips,"HERA CQR GRIP"],
    "SR-3M":[...Accessories,...Grips,"HERA CQR GRIP"],
    "GROZA-4":[...Accessories,...Grips,"HERA CQR GRIP"],
    "MC51":[...Accessories,...Grips],
    "FAL 50.63 PARA":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "1858 CARBINE":[...Accessories,...Grips],
    "AK105":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "JURY":[...Accessories,...Grips],
    "KAC SSR":[...Accessories,...Grips2],
    "GRYOJET CARBINE":[...Accessories,...Grips,"HERA CQR GRIP"],
    "C8A2":[...Accessories,...Grips,"HERA CQR GRIP"],
    "X95R":[...Accessories,...Grips],
    "HK51B":[...Accessories,...Grips],
    "CAN CANNON":[...Accessories,...Grips,"HERA CQR GRIP"],
    //Shotguns
    "KSG 12":[...Accessories,...Grips,"HERA CQR GRIP"],
    "MODEL 870":[...Accessories,...Grips2],
    "DBV12":[...Accessories,...Grips,"HERA CQR GRIP"],
    "KS-23M":[...Accessories,...Grips2],
    "SAIGA-12":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "STEVENDS DB":[...Accessories,...Grips],
    "E-GUN":[...Accessories,...Grips,"HERA CQR GRIP"],
    "AA-12":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "SPAS-12":[...Accessories,...Grips2],
    "DT11":[...Accessories,...Grips],
    "USAS-12":[...Accessories,...Grips,"HERA CQR GRIP"],
    //PDW
    "MP5K":[...Accessories,...Grips],
    "UMP45":[...Accessories,...Grips],
    "G36C":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "MP7":[...Accessories,...Grips,"HERA CQR GRIP"],
    "MAC10":[...Accessories,...Grips,"HERA CQR GRIP"],
    "P90":[...Accessories,...Grips,"HERA CQR GRIP"],
    "COLT MARS":[...Accessories,...Grips],
    "MP5":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "COLT SMG 633":[...Accessories,...Grips2],
    "L2A3":[...Accessories,...Grips],
    "MP5SD":[...Accessories,...Grips,"HERA CQR GRIP"],
    "MP10":[...Accessories,...Grips],
    "M3A1":[...Accessories,...Grips],
    "MP5/10":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "UZI":[...Accessories,...Grips],
    "AUG A3 PARA XS":[...Accessories,...Grips,"HERA CQR GRIP"],
    "K7":[...Accessories,...Grips,"HERA CQR GRIP"],
    "AKS74U":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "PPSH-41":[...Accessories,...Grips],
    "FAL PARA SHORTY":[...Accessories,...Grips2],
    "KRISS VECTOR":[...Accessories,...Grips],
    "PP-19 BIZON":[...Accessories,...Grips,"HERA CQR GRIP"],
    "MP40":[...Accessories,...Grips],
    "X95 SMG":[...Accessories,...Grips],
    "TOMMY GUN":[...Accessories,...Grips],
    "RAMA 1130":[...Accessories,...Grips,"HERA CQR GRIP"],
    "BWC9 A":[...Accessories,...Grips],
    "FIVE-0":[...Accessories,...Grips,"HERA CQR GRIP"],
    //DMRs
    "MK11":[...Accessories,...Grips,"HERA CQR GRIP"],
    "SKS":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "SL-8":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "VSS VINTOREZ":[...Accessories,...Grips],
    "MSG90":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "M21":[...Accessories,...Grips2],
    "BEOWULF TCR":[...Accessories,...Grips,"HERA CQR GRIP"],
    "SA58 SPR":[...Accessories,...Grips,"HERA CQR GRIP"],
    "SCAR SSR":[...Accessories,...Grips,"HERA CQR GRIP"],
    //LMGs
    "COLT LMG":[...Accessories,...Grips],
    "M60":[...Accessories,...Grips,"HERA CQR GRIP"],
    "AUG HBAR":[...Accessories,...Grips,"HERA CQR GRIP"],
    "MG36":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "RPK12":[...Accessories,...Grips,"HERA CQR GRIP"],
    "L86 LSW":[...Accessories,...Grips2],
    "RPK":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "HK21E":[...Accessories,...Grips],
    "HAMR IAR":[...Accessories,...Grips,"HERA CQR GRIP"],
    "RPK74":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "MG3KWS":[...Accessories,...Grips,"HERA CQR GRIP"],
    "MGV-176":[...Accessories,...Grips],
    "STONER 96":[...Accessories,...Grips],
    "MG42":[...Accessories,...Grips,"HERA CQR GRIP"],
    //Sniper rifles
    "INTERVENTION":[...Accessories,...Grips],
    "MODEL 700":[...Accessories,...Grips2],
    "DRAGUNOV SVU":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "AWS":[...Accessories,...Grips,"HERA CQR GRIP"],
    "BFG 50":[...Accessories,...Grips],
    "AWM":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "TRG-42":[...Accessories,...Grips],
    "MOSIN NAGANT":[...Accessories,...Grips2],
    "DRAGUNOV SVDS":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "M1903":[...Accessories,...Grips2],
    "K14":[...Accessories,...Grips,"HERA CQR GRIP"],
    "HECATE II":[...Accessories,...Grips],
    "FT300":[...Accessories,...Grips,"OLYMPIC FOREGRIP","WOOD FURNITURE"],
    "M107":[...Accessories,...Grips,"HERA CQR GRIP"],
    "STERY SCOUT":[...Accessories,...Grips],
    "WA2000":[...Accessories,...Grips2,"HERA CQR GRIP"],
    "NTW-20":[...Accessories,...Grips]
}
//Others
const OAccessories=[
    "DEFAULT",
    "FLASHLIGHT",
    "RED LASER",
    "GREEN LASER",
    "BLUE LASER",
    "YELLOW LASER",
    "TRI LASER",
    "BALLISTICS TRACKER"
]
const OAccessories2=[
    "DEFAULT",
    "FLASHLIGHT",
    "RED LASER",
    "GREEN LASER",
    "BLUE LASER",
    "YELLOW LASER",
    "TRI LASER",
]
const CantedSight=[
    "CANTED IRON SIGHT",
    "CANTED DELTA SIGHT",
    "CANTED ACOG SCOPE",
    "CANTED ANIMU SIGHT",
    "CANTED FURRO SIGHT"
]
const Stocks=[
    "RETRACT STOCK"
]
const POther={
    "DEFAULT":[...OAccessories,...CantedSight],
     //ARs
    "AK12":[...OAccessories,...CantedSight,...Stocks],
    "AN-94":[...OAccessories,...CantedSight,...Stocks],
    "AS VAL":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK"],
    "SCAR-L":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK"],
    "AUG A1":[...OAccessories,...CantedSight],
    "M16A4":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK","COLLAPSIBLE STOCK"],
    "G36":[...OAccessories,...CantedSight,...Stocks],
    "M16A1":[...OAccessories,...CantedSight],
    "M16A3":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK","COLLAPSIBLE STOCK","BURST GROUPING"],
    "TYPE 20":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK","EXTEND STOCK"],
    "AUG A2":[...OAccessories,...CantedSight],
    "K2":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK"],
    "FAMAS F1":[...OAccessories,...CantedSight,"FAMAS G2"],
    "AK47":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK","COLLAPSIBLE STOCK"],
    "AUG A3":[...OAccessories,...CantedSight],
    "L85A2":[...OAccessories,...CantedSight],
    "HK416":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK"],
    "AK74":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK","COLLAPSIBLE STOCK"],
    "AKM":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK","COLLAPSIBLE STOCK"],
    "AK103":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK"],
    "TAR-21":[...OAccessories,...CantedSight],
    "TYPE-88":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK","REMOVE STOCK"],
    "M231":[...OAccessories,...CantedSight,"WIRE STOCK"],
    "C7A2":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK","REMOVE STOCK"],
    "STG-44":[...OAccessories],
    "G11K2":[...OAccessories,...CantedSight],
    "M14":[...OAccessories],
    "BEOWULF ECR":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK","COLLAPSIBLE STOCK"],
    "SCAR-H":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK"],
    "AK12BR":[...OAccessories,...CantedSight,...Stocks],
    "G3A3":[...OAccessories,...CantedSight,...Stocks,"COLLAPSIBLE STOCK"],
    "AG-3":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK"],
    "HK417":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK"],
    "HENRY 45-70":[...OAccessories,...CantedSight,"REMOVE STOCK","MARKSMAN KIT"],
    "FAL 50.00":[...OAccessories,...CantedSight],
    //Carbine
    "M4A1":[...OAccessories,...CantedSight,"FULL STOCK","REMOVE STOCK",...Stocks],
    "G36K":[...OAccessories,...CantedSight,...Stocks],
    "M4":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK","REMOVE STOCK"],
    "L22":[...OAccessories,...CantedSight],
    "SCAR PDW":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK","REMOVE STOCK"],
    "AKU12":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK"],
    "GROZA-1":[...OAccessories,...CantedSight],
    "OTS-126":[...OAccessories,...CantedSight,...Stocks,"COLLAPSIBLE STOCK","MAGAZINE STOCK"],
    "AK12C":[...OAccessories,...CantedSight,...Stocks],
    "HONEY BADGER":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK","REMOVE STOCK"],
    "K1A":[...OAccessories,...CantedSight,...Stocks],
    "SR-3M":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK"],
    "GROZA-4":[...OAccessories,...CantedSight],
    "MC51":[...OAccessories,...CantedSight,"EXTEND STOCK"],
    "FAL 50.63 PARA":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK"],
    "1858 CARBINE":[...OAccessories,...CantedSight,...Stocks],
    "AK105":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK"],
    "JURY":[...OAccessories,...CantedSight,"SPEEDLOADER"],
    "KAC SSR":[...OAccessories,...CantedSight,"SPEEDLOADER"],
    "GRYOJET CARBINE":[...OAccessories,...CantedSight,"AUTOMATIC"],
    "C8A2":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK","REMOVE STOCK"],
    "X95R":[...OAccessories,...CantedSight],
    "HK51B":[...OAccessories,...CantedSight,"EXTEND STOCK","FULL STOCK"],
    "CAN CANNON":[...OAccessories,...CantedSight,"MARKSMAN KIT"],
    //Shotguns
    "KSG 12":[...OAccessories,...CantedSight],
    "MODEL 870":[...OAccessories,...CantedSight,"EXTENDED TUBE","REMOVE STOCK"],
    "DBV12":[...OAccessories,...CantedSight,...Stocks],
    "KS-23M":[...OAccessories,...CantedSight,"FULL-STOCK","REMOVE STOCK"],
    "SAIGA-12":[...OAccessories,...CantedSight,"REMOVE STOCK",...Stocks],
    "STEVENDS DB":[...OAccessories,...CantedSight,"REMOVE STOCK"],
    "E-GUN":[...OAccessories,...CantedSight,"CROWD CONTROL","HOME DEFENSE SETUP"],
    "AA-12":[...OAccessories,...CantedSight,"SEMI-AUTO CONV."],
    "SPAS-12":[...OAccessories,...CantedSight,"PUMP ACTION"],
    "DT11":[...OAccessories,...CantedSight,"REMOVE STOCK","OLYMPIAN STOCK","SPORTING STOCK"],
    "USAS-12":[...OAccessories,...CantedSight,"SEMI-AUTO CONV."],
    //PDW
    "MP5K":[...OAccessories,...CantedSight,"BURST GROUPING","MP5K STOCK"],
    "UMP45":[...OAccessories,...CantedSight],
    "G36C":[...OAccessories,...CantedSight,...Stocks],
    "MP7":[...OAccessories,...CantedSight,"EXTENDED MAGAZINE",...Stocks],
    "MAC10":[...OAccessories,...CantedSight,"EXTENDED STOCK","FULL STOCK"],
    "P90":[...OAccessories,...CantedSight,"30RD MAG"],
    "COLT MARS":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK","REMOVE STOCK"],
    "MP5":[...OAccessories,...CantedSight,"BURST GROUPING"],
    "COLT SMG 633":[...OAccessories,...CantedSight,"BURST GROUPING","REMOVE STOCK","FULL STOCK",...Stocks],
    "L2A3":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK",...Stocks],
    "MP5SD":[...OAccessories,...CantedSight,"BURST GROUPIGN"],
    "MP10":[...OAccessories,...CantedSight,"FLASHLIGHT OFF"],
    "M3A1":[...OAccessories,...CantedSight,...Stocks],
    "MP5/10":[...OAccessories,...CantedSight,..."BURST GROUPING","REMOVE STOCK",...Stocks],
    "UZI":[...OAccessories,...CantedSight,"EXTENDED STOCK","FULL STOCK"],
    "AUG A3 PARA XS":[...OAccessories,...CantedSight],
    "K7":[...OAccessories,...CantedSight,...Stocks],
    "AKS74U":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK","REMOVE STOCK"],
    "PPSH-41":[...OAccessories,...CantedSight,"REMOVE STOCK"],
    "FAL PARA SHORTY":[...OAccessories,...CantedSight,"FULL STOCK","EXTEND STOCK"],
    "KRISS VECTOR":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK"],
    "PP-19 BIZON":[...OAccessories,...CantedSight,"FULL STOCK","REMOVE STOCK"],
    "MP40":[...OAccessories,...CantedSight,...Stocks],
    "X95 SMG":[...OAccessories,...CantedSight],
    "TOMMY GUN":[...OAccessories,...CantedSight,"30RD MAG","50RD DRUM","M1919 CONV","REMOVE STOCK"],
    "RAMA 1130":[...OAccessories],
    "BWC9 A":[...OAccessories,...CantedSight,"SEMI-AUTO CONV.","BURST CONV."],
    "FIVE-0":[...OAccessories,...CantedSight,"FULL-AUTO CONV.","REMOVE STOCK"],
    //DMRs
    "MK11":[...OAccessories,...CantedSight,...Stocks,"COLLAPSIBLE STOCK","REMOVE STOCK"],
    "SKS":[...OAccessories,...CantedSight,...Stocks,"FULL STOCK"],
    "SL-8":[...OAccessories,...CantedSight],
    "VSS VINTOREZ":[...OAccessories,...CantedSight,...Stocks,"COLLAPSIBLE STOCK"],
    "MSG90":[...OAccessories,...CantedSight],
    "M21":[...OAccessories],
    "BEOWULF TCR":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK","FULL STOCK"],
    "SA58 SPR":[...OAccessories,...CantedSight],
    "SCAR SSR":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK"],
    //LMGs
    "COLT LMG":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK","COLLAPSIBLE STOCK"],
    "M60":[...OAccessories,...CantedSight,"REMOVE STOCK"],
    "AUG HBAR":[...OAccessories,...CantedSight,"CLOSED BOLT CONV."],
    "MG36":[...OAccessories,...CantedSight,...Stocks],
    "RPK12":[...OAccessories,...CantedSight,...Stocks],
    "L86 LSW":[...OAccessories,...CantedSight],
    "RPK":[...OAccessories,...CantedSight],
    "HK21E":[...OAccessories,...CantedSight],
    "HAMR IAR":[...OAccessories,...CantedSight,...Stocks,"REMOVE STOCK"],
    "RPK74":[...OAccessories,...CantedSight],
    "MG3KWS":[...OAccessories,...CantedSight,"HEAVY BOLT","FULL STOCK",...Stocks],
    "MGV-176":[...OAccessories,...CantedSight,"FOLD STOCK"],
    "STONER 96":[...OAccessories,...CantedSight],
    "MG42":[...OAccessories,...CantedSight,"HEAVY BOLT","LIGHT BOLT"],
    //Sniper rifles
    "INTERVENTION":[...OAccessories,...CantedSight,"MARKSMAN KIT","REMOVE STOCK"],
    "MODEL 700":[...OAccessories,...CantedSight,"EXTENDED MAGAZINE","MARKSMAN KIT"],
    "DRAGUNOV SVU":[...OAccessories,...CantedSight,"SVU-A CONVERSION"],
    "AWS":[...OAccessories,...CantedSight,"MARKSMAN KIT"],
    "BFG 50":[...OAccessories,...CantedSight,"REMOVE STOCK"],
    "AWM":[...OAccessories,...CantedSight,"MARKSMAN KIT"],
    "TRG-42":[...OAccessories,...CantedSight,"MARKSMAN KIT","REMOVE STOCK"],
    "MOSIN NAGANT":[...OAccessories,...CantedSight,"EXTENDED MAG","MARKSMAN KIT"],
    "DRAGUNOV SVDS":[...OAccessories,...CantedSight,"REMOVE STOCK","RETRACT STOCK","FULL STOCK"],
    "M1903":[...OAccessories,...CantedSight,"MARKSMAN KIT","REMOVE STOCK"],
    "K14":[...OAccessories,...CantedSight,"MARKSMAN KIT","REMOVE STOCK"],
    "HECATE II":[...OAccessories,...CantedSight,"MARKSMAN KIT","REMOVE STOCK"],
    "FT300":[...OAccessories,...CantedSight,"MARKSMAN KIT","REMOVE STOCK"],
    "M107":[...OAccessories,...CantedSight,"EXTENDED MAG"],
    "STERY SCOUT":[...OAccessories,...CantedSight,"MARKSMAN KIT"],
    "WA2000":[...OAccessories,...CantedSight],
    "NTW-20":[...OAccessories,"MARKSMAN KIT"]
}
const SOther={
    "DEFAULT":[...OAccessories2,...CantedSight],
    "G17":[...OAccessories2,"G STOCK"],
    "M9":[...OAccessories2,"EXTENDED MAGAZINE","RAFFICA STOCK"],
    "M1911A1":[...OAccessories2,"SHOULDER STOCK","ENGRAVINGS"],
    "DESERT EAGLE L5":[...OAccessories2],
    "G21":[...OAccessories2,"G STOCK"],
    "G23":[...OAccessories2,"G STOCK"],
    "M45A1":[...OAccessories2,"EXTENDED MAGAZINE","SHOULDER STOCK"],
    "G40":[...OAccessories2,"G STOCK"],
    "KG-99":[...OAccessories2,"FULL STOCK"],
    "G50":[...OAccessories2,"G STOCK"],
    "FIVE SEVEN":[...OAccessories2,"EXTENDED MAGAZINE"],
    "ZIP 22":[...OAccessories,"PRO MAG"],
    "GI M1":[...OAccessories2,"SHOULDER STOCK"],
    "HARDBALLER":[...OAccessories2,"SHOULDER STOCK"],
    "IZHEVSK PB":[...OAccessories2,"12RD MAGAZINE","EXTENDED MAGAZINE"],
    "MAKAROV PM":[...OAccessories2,"12RD MAGAZINE","EXTENDED MAGAZINE"],
    "GB-22":[...OAccessories],
    "DESERT EAGLE XIX":[...OAccessories2,"POLICE STOCK"],
    "AUTOMAG III":[...OAccessories2],
    "GYROJET MARK I":[...OAccessories2,"AUTOMATIC"],
    "GSP":[...OAccessories2],
    "GRIZZLY":[...OAccessories2],
    "M2011":[...OAccessories2,"SHOULDER STOCK"],
    "ALIEN":[...OAccessories2],
    "AF2011-A1":[...OAccessories2, "SHOULDER STOCK"],
    //Machine Pistols
    "G18C":[...OAccessories2,"G STOCK","FOLDED STOCK"],
    "93R":[...OAccessories2,"RAFFICA STOCK"],
    "PP-2000":[...OAccessories,"RETRACT STOCK","MAGAZINE STOCK"],
    "TEC-9":[...OAccessories2,"FULL STOCK"],
    "MICRO UZI":[...OAccessories,"FULL STOCK",...CantedSight],
    "ŠKORPION VZ.61":[...OAccessories2,"REMOVE LIMITER","EXTENDED STOCK","FULL STOCK"],
    "ASMI":[...OAccessories,...CantedSight,...Grips,"REMOVE STOCK","RETRACT STOCK"],
    "MP1911":[...OAccessories2,"REMOVE STOCK"],
    "ARM PISTOL":[...OAccessories,"EXTENDED MAGAZINE"],
    //Revolvers
    "MP412 REX":[...OAccessories,"SPEEDLOADER"],
    "MATEBA 6":[...OAccessories,"SPEEDLOADER"],
    "1858 NEW ARMY":[...OAccessories],
    "REDHAWK 44":[...OAccessories,"SPEEDLOADER","KAC STOCK"],
    "JUDGE":[...OAccessories,"SPEEDLOADER","TAURUS STOCK"],
    "EXECUTIONER":[...OAccessories,"SPEEDLOADER","TAURUS STOCK"],
    //Other
    "SUPER SHORTY":[...OAccessories,"EXTENDED TUBE",...CantedSight],
    "SFG 50":[...OAccessories,...CantedSight,"REMOVE STOCK"],
    "M79 THUMPER":[...OAccessories,"REMOVE STOCK"],
    "ADVANCED COILGUN":[...OAccessories,...CantedSight,"CROWD CONTROL","HOME DEFENSE SETUP"],
    "SAWED OFF":[...OAccessories,...CantedSight,"BOOM STOCK"],
    "SAIGA-12U":[...OAccessories,...CantedSight,"FULL STOCK"],
    "OBREZ":[...OAccessories,...CantedSight,"EXTENDED MAGAZINE","MARKSMAN KIT","OBREZ STOCK"],
    "SASS 308":[...OAccessories]
}
//Ammo
const Ammo=[
    "DEFAULT",
    "ARMOR PIERCING",
    "HOLLOW POINT",
    "TRACERLESS",
]
const Ammo2=[
    "DEFAULT",
    "ARMOR PIERCING",
    "HOLLOW POINT",
    "TRACERLESS",
    ".223 REM"
]
const Ammo3=[
    "DEFAULT",
    "FLECHETTE",
    "BIRDSHOT",
    "SLUGS",
    "RUBBER PELLETS"
]
const PAmmo={
    "DEFAULT":[...Ammo],
     //ARs
    "AK12":[...Ammo,"SUPER ARMOR PIERCING"],
    "AN-94":[...Ammo,"7.62X39MM","SUPER ARMOR PIERCING"],
    "AS VAL":[...Ammo,"EXTENDED MAG"],
    "SCAR-L":[...Ammo,"9X19MM",".223 REM"],
    "AUG A1":[...Ammo,"9X19MM",".223 REM"],
    "M16A4":[...Ammo,"7.62X39MM",".223 REM",".25-45 SHARPS"],
    "G36":[...Ammo,".300 BLK",".223 REM"],
    "M16A1":[...Ammo,"M855",".223 REM"],
    "M16A3":[...Ammo,"7.62X39MM",".223 REM",".25-45 SHARPS"],
    "TYPE 20":[...Ammo,"EXTENDED MAG","EXTENDED MAG","60RD DRUM"],
    "AUG A2":[...Ammo,"7.62X39MM",".223 REM"],
    "K2":[...Ammo,".223 REM","7.62X39MM"],
    "FAMAS F1":[...Ammo,".223 REM"],
    "AK47":[...Ammo],
    "AUG A3":[...Ammo,".300 BLK",".223 REM"],
    "L85A2":[...Ammo,".223 REM"],
    "HK416":[...Ammo,".300 BLK",".223 REM"],
    "AK74":[...Ammo,"SUPER ARMOR PIERCING"],
    "AKM":[...Ammo,"BANANA",".366 SHOT",".366 SP"],
    "AK103":[...Ammo,"5.5X45MM"],
    "TAR-21":[...Ammo,"DUPLEX",".223 REM"],
    "TYPE-88":[...Ammo,"SUPER ARMOR PIERCING","30RD MAG","7.62X39MM"],
    "M231":[...Ammo,"M855",".223 REM"],
    "C7A2":[...Ammo,".223 REM","7.62X39MM",".20 TACT"],
    "STG-44":[...Ammo,"5.5X45MM"],
    "G11K2":[...Ammo],
    //BRs
    "M14":[...Ammo,"SILENT","6.5MM"],
    "BEOWULF ECR":[...Ammo,".458 SOCOM","5.56X45MM",".410 BORE"],
    "SCAR-H":[...Ammo,"SILENT","7.62X39MM"],
    "AK12BR":[...Ammo,"7.62X39MM","12.7X55MM"],
    "G3A3":[...Ammo,"SILENT",".45 ACP"],
    "AG-3":[...Ammo,"SILENT"],
    "HK417":[...Ammo,"SILENT"],
    "HENRY 45-70":["PLUS P","TRACERLESS",".30-30",".357 MAGNUM",".410 BORE","DEFAULT"],
    "FAL 50.00":[...Ammo,"SILENT","5.56X45MM",".45 ACP"],
    //Carbines
    "M4A1":[...Ammo,".223 REM","7.62X39MM",".25-45 SHARPS"],
    "M4":[...Ammo,".223 REM","7.62X39MM",".25-45 SHARPS"],
    "G36K":[...Ammo,".223 REM",".300 BLK"],
    "L22":[...Ammo,".223 REM"],
    "SCAR PDW":[...Ammo,".223 REM","9X19MM","7.62X51MM",],
    "AKU12":[...Ammo,"SUPER ARMOUR PIERCING","9X19MM"],
    "GROZA-1":[...Ammo,"5.45x39MM","5.56X45MM"],
    "OTS-126":["DEFAULT","HOLLOW POINT","TRACERLESS","SUPER ARMOUR PIERCING"],
    "AK12C":[...Ammo,"9X39MM"],
    "HONEY BADGER":[...Ammo],
    "K1A":[...Ammo,".233 REM","7.62X39MM"],
    "SR-3M":[...Ammo,"EXTENDED MAGAZINE"],
    "GROZA-4":[...Ammo],
    "MC51":[...Ammo,"SILENT"],
    "FAL 50.63 PARA":[...Ammo,"SILENT","5.56X45MM",".45 ACP"],
    "1858 CARBINE":["DEFAULT","TRACERLESS",".36 CALIBER","SNAKE SHOT"],
    "AK105":[...Ammo,"SUPER ARMOR PIERCING","5.56X45MM"],
    "JURY":["DEFAULT",".410 BORE","FLECHETTE","BIRDSHOT","RUBBER PELLETS","EXOTIC SLUGS","TRACERLESS"],
    "KAC SSR":["DEFAULT","TRACERLESS"],
    "GRYOJET CARBINE":["DEFAULT","12MM ROCKET"],
    "C8A2":[...Ammo,".223 REM","7.62X39MM",".20 TACT"],
    "X95R":[...Ammo,"SUPER ARMOR PIERCING","5.56X45MM",".300 BLK"],
    "HK51B":[...Ammo,"SILENT"],
    "CAN CANNON":["DEFAULT",".223 BLANKS","7.62X39 BLANKS",".50 BEOWULF BLANKS"],
    //Shotguns
    "KSG 12":[...Ammo3,"MINISHELL","MINISLUGS"],
    "MODEL 870":[...Ammo3,"MINISHELL","MINISLUGS"],
    "DBV12":[...Ammo3,".30-06",".410 BORE"],
    "KS-23M":["SHRAPNEL-25","VOLNA-R","BARRIKADA","HARPOON","4 GAUGE"],
    "SAIGA-12":[...Ammo3,".223 REM","9X19MM",'7.62X39MM',".308 WIN","9.6X53MM",".50 BMG","FULL-AUTP CONV."],
    "STEVENDS DB":[...Ammo3],
    "E-GUN":["DEFAULT","HEAVY DISCS","LIGHT DISCS","PENNIES"],
    "AA-12":[...Ammo3,"20RD DRUM"],
    "SPAS-12":[...Ammo3,"MINISHELL","MINISLUGS"],
    "DT11":["DEFAULT","#000 BUCKSHOT","3.5 SHELL","BOLO ROUND","SLUGS"],
    "USAS-12":[...Ammo3],
    //PDW
    "MP5K":[...Ammo,"PLUS P","10MM AUTO"],
    "UMP45":[...Ammo,"PLUS P",".45 SUPER",".40 S&W"],
    "G36C":[...Ammo2,".300 BLK"],
    "MP7":[...Ammo],
    "MAC10":[...Ammo,"PLUS P",".45 SUPER","9X19MM"],
    "P90":[...Ammo],
    "COLT MARS":[...Ammo,"9X30MM MARS"],
    "MP5":[...Ammo,"PLUS P"],
    "COLT SMG 633":[...Ammo,"PLUS P"],
    "L2A3":[...Ammo,"PLUS P",".45 ACP"],
    "MP5SD":[...Ammo,"PLUS P"],
    "MP10":[...Ammo,"PLUS P"],
    "M3A1":[...Ammo,"PLUS P",".45 SUPER","TYPE 37 CONV."],
    "MP5/10":[...Ammo,"PLUS P",".40 S&W"],
    "UZI":[...Ammo,"PLUS P",".45 ACP",".41 AE",".22 LR"],
    "AUG A3 PARA XS":[...Ammo,"PLUS P",".40 S&W"],
    "K7":[...Ammo,"PLUS P","5.56X45MM"],
    "AKS74U":[...Ammo,"SUPER ARMOR PIERCING","9X19MM","7.62X39MM"],
    "PPSH-41":[...Ammo,"35RD BOX MAG"],
    "FAL PARA SHORTY":[...Ammo,"SILENT","5.56X45MM",".45 ACP"],
    "KRISS VECTOR":[...Ammo,".45 SUPER","ARMOR PIERCING","9X19MM",".357 SIG",".22 LR"],
    "PP-19 BIZON":[...Ammo,"PLUS P","9X18MM",'7.62X25MM'],
    "MP40":[...Ammo,"PLUS P",],
    "X95 SMG":[...Ammo,"PLUS P","TRIPLEX","5.56X30MM MINSAS"],
    "TOMMY GUN":[...Ammo,"PLUS P",".45 SUPER","10MM AUTO"],
    "RAMA 1130":[...Ammo,"PLUS P",".380 ACP"],
    "BWC9 A":[...Ammo,"PLUS P","EXTENDED MAG","REDUCED MAG"],
    "FIVE-0":[...Ammo,".45 ACP","9X19MM"],
    //DMRs
    "MK11":[...Ammo,"SILENT","DEPLETED URANIUM"],
    "SKS":[...Ammo,".366 SHOT",".366 TKM POLYMER SLUG"],
    "SL-8":[...Ammo2,".300 WHISPER"],
    "VSS VINTOREZ":[...Ammo,"7.62X39MM"],
    "MSG90":[...Ammo,"SILENT",".308 WIN"],
    "M21":[...Ammo,"SILENT","6.5MM"],
    "BEOWULF TCR":[...Ammo,".458 SOCOM","5.56X45MM"],
    "SA58 SPR":[...Ammo,"SILENT","5.56X45MM",".45 ACP"],
    "SCAR SSR":[...Ammo,"SILENT","6.5MM"],
    //LMGs
    "COLT LMG":[...Ammo2,"7.62X39MM",".20 TACTICAL"],
    "M60":[...Ammo,"SILENT"],
    "AUG HBAR":[...Ammo2,".22 LR"],
    "MG36":[...Ammo2,".300 BLK"],
    "RPK12":[...Ammo,"SUPER ARMOR PIERCING","7.62X39MM"],
    "L86 LSW":[...Ammo2],
    "RPK":[...Ammo],
    "HK21E":[...Ammo,"SILENT"],
    "HAMR IAR":[...Ammo,"30RD STANAG",".223 REM"],
    "RPK74":[...Ammo,"SUPER ARMOR PIERCING"],
    "MG3KWS":[...Ammo,"SILENT","DEPLETED URANIUM"],
    "MGV-176":[...Ammo],
    "STONER 96":[...Ammo],
    "MG42":[...Ammo],
    //Sniper rifles
    "INTERVENTION":["DEFAULT",".375 CHEYTAC","TRACERLESS"],
    "MODEL 700":["DEFAULT","SILENT","TRACERLESS",".32 ACP"],
    "DRAGUNOV SVU":["DEFAULT","TRACERLESS","9.6X53MM"],
    "AWS":["DEFAULT","TRACERLESS","SILENT"],
    "BFG 50":["DEFAULT","TRACERLESS",".416 BARRETT","M903 SLAP","RAT SHOT",".17 INCINERATOR"],
    "AWM":["DEFAULT","TRACERLESS",".338 NORMA",".308 WIN"],
    "TRG-42":["DEFAULT","TRACERLESS","TRG-22 KIT",".338 NORMA","TRG-S KIT"],
    "MOSIN NAGANT":["DEFAULT","TRACERLESS","8X50MMR",".410 BORE"],
    "DRAGUNOV SVDS":["DEFAULT","TRACERLESS","10/3.5MM","9.6X53MM"],
    "M1903":["DEFAULT","TRACERLESS","ARMOR PIERCING","AIR SERVICE MAG","PEDERSEN DEVICE"],
    "K14":["DEFAULT","TRACERLESS","SILENT",".308 WIN"],
    "HECATE II":["DEFAULT","TRACERLESS",".416 BARRETT","M903 SLAP","RAT SHOT",".17 INCINERATOR"],
    "FT300":["DEFAULT","TRACERLESS","6XC",".22 LR","7.5X55MM",".308 WIN"],
    "M107":["DEFAULT","TRACERLESS",".416 BARRETT","M903 SLAP","RAT SHOT",".17 INCINERATOR"],
    "STERY SCOUT":["DEFAULT","TRACERLESS","SILENT",".376 STEYR","5.56X45MM"],
    "WA2000":["DEFAULT","TRACERLESS","SILENT","7.5X55MM",".300 WINMAG"],
    "NTW-20":["DEFAULT","TRACERLESS","20X110MM","14.5MM"]
}
const SAmmo={
    "DEFAULT":[...Ammo],
    "G17":[...Ammo,"33RD MAG","PLUS P"],
    "M9":[...Ammo,"PLUS P"],
    "M1911A1":[...Ammo,"PLUS P",".45 SUPER","RATSHOT","DART"],
    "DESERT EAGLE L5":[...Ammo,".44 SPECIAL",".357 MAGNUM"],
    "G21":[...Ammo,"PLUS P",".45 SUPER","26RD MAG"],
    "G23":[...Ammo,"22RD MAG"],
    "M45A1":[...Ammo,"PLUS P",".45 SUPER","DART"],
    "G40":[...Ammo,"PLUS P","30RD MAG"],
    "KG-99":[...Ammo,"PLUS P","EXTENDED MAG"],
    "G50":[...Ammo],
    "FIVE SEVEN":[...Ammo],
    "ZIP 22":[...Ammo,"RAT SHOT"],
    "GI M1":[...Ammo],
    "HARDBALLER":[...Ammo,"PLUS P"],
    "IZHEVSK PB":[...Ammo,"PLUS P"],
    "MAKAROV PM":[...Ammo,"PLUS P"],
    "GB-22":[...Ammo,"PLUS P","10MM AUTO","MINISHELLS",".50 AE"],
    "DESERT EAGLE XIX":[...Ammo,".357 MAGNUM"],
    "AUTOMAG III":[...Ammo,".45 WINMAG",".50 AE"],
    "GYROJET MARK I":["DEFAULT","12MM ROCKET"],
    "GSP":[...Ammo,".32 S&W","GSP RAT SHOT"],
    "GRIZZLY":[...Ammo],
    "M2011":[...Ammo,"PLUS P"],
    "ALIEN":[...Ammo,"PLUS P"],
    "AF2011-A1":[...Ammo,"PLUS P",".45 SUPER","DOUBLE DART"],
    //Machine Pistols
    "G18C":[...Ammo,"PLUS P","33RD MAG"],
    "93R":[...Ammo,"PLUS P"],
    "PP-2000":[...Ammo],
    "TEC-9":[...Ammo,"PLUS P","EXTENDED MAGAZINE"],
    "MICRO UZI":[...Ammo,"PLUS P",".45 ACP","STRIKE-3"],
    "ŠKORPION VZ.61":[...Ammo,"PLUS P","9X18MM","RAT SHOT","RUBBER PELLETS"],
    "ASMI":[...Ammo,"PLUS P"],
    "MP1911":[...Ammo,"PLUS P",".45 SUPER","9X18MM"],
    "ARM PISTOL":[...Ammo,".223 REM"],
    //Revolvers
    "MP412 REX":[...Ammo,".38 SPECIAL"],
    "MATEBA 6":[...Ammo,".44 SPECIAL"],
    "1858 NEW ARMY":[...Ammo,".38 CALIBER","SNAKE SHOT"],
    "REDHAWK 44":[...Ammo,".44 SPECIAL",".48 LONG COLT"],
    "JUDGE":[...Ammo3],
    "EXECUTIONER":[...Ammo],
    //Other
    "SUPER SHORTY":[...Ammo3,"MINISHELL",'MINISLUGS'],
    "SFG 50":["DEFAULT",".416 BARRETT","TRACERLESS","M903 SLAP","RAT SHOT",".17 INCINERATOR"],
    "M79 THUMPER":["DEFAULT","SPONGE",".410 BEEHIVE","ARMOR PIERCING","BUCKSHOT","HOLLOW POINT","FLECHETTE","TRACERLESS","DOUBLE SLUGS"],
    "ADVANCED COILGUN":["HEAVY DISCS","LIGHT DISCS","PENNIES"],
    "SAWED OFF":[...Ammo3],
    "SAIGA-12U":[...Ammo3,"EXTENDED MAGAZINE",".223 REM","7.62X39MM","9X19MM",".308 WIN","9.6X53MM",".50BMG","FULL AUTO CONV."],
    "OBREZ":["DEFAULT","TRACERLESS","8X50MMR",".410 BORE"],
    "SASS 308":[...Ammo,"SILENT",".358 WIN"]
}
function randomizePrimary(Primary){
    let randomPOptic = POptics[Primary][Math.floor(Math.random() * POptics[Primary].length)];
    PrimaryOptic.innerText=randomPOptic;
    let randomPBarrel = PBarrels[Primary][Math.floor(Math.random() * PBarrels[Primary].length)];
    PrimaryBarrel.innerText=randomPBarrel;
    let randomPUnderarrel = PUnderbarrels[Primary][Math.floor(Math.random() * PUnderbarrels[Primary].length)];
    PrimaryUnderbarrel.innerText=randomPUnderarrel;
    let randomPOther = POther[Primary][Math.floor(Math.random() * POther[Primary].length)];
    PrimaryOther.innerText=randomPOther;
    let randomPAmmo = PAmmo[Primary][Math.floor(Math.random() * PAmmo[Primary].length)];
    PrimaryAmmo.innerText=randomPAmmo;
}
function randomizeSecondary(Secondary){
    let randomSOptic = SOptics[Secondary][Math.floor(Math.random() * SOptics[Secondary].length)];
    SecondaryOptic.innerText=randomSOptic;
    let randomSBarrel = SBarrels[Secondary][Math.floor(Math.random() * SBarrels[Secondary].length)];
    SecondaryBarrel.innerText=randomSBarrel;
    let randomSOther = SOther[Secondary][Math.floor(Math.random() * SOther[Secondary].length)];
    SecondaryOther.innerText=randomSOther;
    let randomSAmmo = SAmmo[Secondary][Math.floor(Math.random() * SAmmo[Secondary].length)];
    SecondaryAmmo.innerText=randomSAmmo;
}

function randomizeAttachments(Primary,Secondary){
    if(!(Primary in POptics)){
        Primary="DEFAULT";
        PrimaryError.innerText="Primary weapon does not have designated attachment selection. Using default list"
    }else{
        PrimaryError.innerText="";
    }
    if(!(Secondary in SOptics)){
        Secondary="DEFAULT";
        SecondaryError.innerText="Secondary weapon does not have designated attachment selection. Using default list"
    }else{
        SecondaryError.innerText="";
    }
    //Primary block
    randomizePrimary(Primary);
    //Secondary block
    randomizeSecondary(Secondary);
}
console.log(Primaries.length+Secondaries.length)
var randomPrimary;
var randomSecondary;
function randomize(){
    
    //Primary
    let randomPNumber=Math.floor(Math.random() * Primaries.length);
    randomPrimary= Primaries[randomPNumber][0];
    header1.innerText=randomPrimary+" - "+Primaries[randomPNumber][2]+" Rank "+Primaries[randomPNumber][1];
    console.log(randomPrimary)
    //Secondary
    let randomSnumber=Math.floor(Math.random() * Secondaries.length);
    randomSecondary = Secondaries[randomSnumber][0];
    header2.innerText=randomSecondary+" - "+Secondaries[randomSnumber][2]+" Rank "+Secondaries[randomSnumber][1];
    randomizeAttachments(randomPrimary,randomSecondary);
    //Grenade
    let randomGNumber=Math.floor(Math.random() * Grenades.length);
    let randomGrenade = Grenades[randomGNumber][0];
    Grenade.innerText=randomGrenade+" - "+Grenades[randomGNumber][2]+" Rank "+Grenades[randomGNumber][1];;
    //Melee
    let randomMNumber=Math.floor(Math.random() * Melees.length);
    let randomMelee = Melees[randomMNumber][0];
    Melee.innerText=randomMelee+" - "+Melees[randomMNumber][1];
}
const button=document.getElementById("randButton");
button.addEventListener('click',function(){
    randomize();
});
const wepAttachRerollButton1=document.getElementById("primaryAttachments");
wepAttachRerollButton1.addEventListener('click',function(){
    randomizePrimary(randomPrimary);
})
const wepAttachRerollButton2=document.getElementById("secondaryAttachments");
wepAttachRerollButton2.addEventListener('click',function(){
    randomizeSecondary(randomSecondary);
})