const Primaries=[
    //ARs
    ["AK12",0,"Assault Rifle"],
    ["AN-94",10,"Assault Rifle"],
    ["AS VAL",15,"Assault Rifle"],
    ["SCAR-L",16,"Assault Rifle"],
    ["AUG A1",20,"Assault Rifle"],
    ["M16A4",22,"Assault Rifle"],
    ["G36",25,"Assault Rifle"],
    ["M16A1",28,"Assault Rifle"],
    ["M16A3",31,"Assault Rifle"],
    ["TYPE 20",37,"Assault Rifle"],
    ["AUG A2",39,"Assault Rifle"],
    ["K2",42,"Assault Rifle"],
    ["FAMAS F1",45,"Assault Rifle"],
    ["AK47",47,"Assault Rifle"],
    ["AUG A3",52,"Assault Rifle"],
    ["L85A2",55,"Assault Rifle"],
    ["HK416",64,"Assault Rifle"],
    ["AK74",74,"Assault Rifle"],
    ["AKM",94,"Assault Rifle"],
    ["AK103",103,"Assault Rifle"],
    ["TAR-21",111,"Assault Rifle"],
    ["TYPE-88",122,"Assault Rifle"],
    ["M231",123,"Assault Rifle"],
    ["C7A2",128,"Assault Rifle"],
    ["STG-44",144,"Assault Rifle"],
    ["G11K2",211,"Assault Rifle"],
    //BRs
    ["M14",2,"Battle Rifle"],
    ["BEOWULF ECR",21,"Battle Rifle"],
    ["SCAR-H",30,"Battle Rifle"],
    ["AK12BR",44,"Battle Rifle"],
    ["G3A3",59,"Battle Rifle"],
    ["AG-3",76,"Battle Rifle"],
    ["HK417",76,"Battle Rifle"],
    ["HENRY 45-70",96,"Battle Rifle"],
    ["FAL 50.00",107,"Battle Rifle"],
    //Carbines
    ["M4A1",0,"Carbine"],
    ["G36K",6,"Carbine"],
    ["M4",14,"Carbine"],
    ["L22",28,"Carbine"],
    ["SCAR PDW",32,"Carbine"],
    ["AKU12",35,"Carbine"],
    ["GROZA-1",42,"Carbine"],
    ["OTS-126",48,"Carbine"],
    ["AK12C",51,"Carbine"],
    ["HONEY BADGER",62,"Carbine"],
    ["K1A",63,"Carbine"],
    ["SR-3M",69,"Carbine"],
    ["GROZA-4",79,"Carbine"],
    ["MC51",86,"Carbine"],
    ["FAL 50.63 PARA",89,"Carbine"],
    ["1858 CARBINE",93,"Carbine"],
    ["AK105",105,"Carbine"],
    ["JURY",114,"Carbine"],
    ["KAC SSR",125,"Carbine"],
    ["GRYOJET CARBINE",127,"Carbine"],
    ["C8A2",128,"Carbine"],
    ["X95R",130,"Carbine"],
    ["HK51B",157,"Carbine"],
    ["CAN CANNON",222,"Carbine"],
    //Shotguns
    ["KSG 12",1,"Shotgun"],
    ["MODEL 870",11,"Shotgun"],
    ["DBV12",24,"Shotgun"],
    ["KS-23M",56,"Shotgun"],
    ["SAIGA-12",63,"Shotgun"],
    ["STEVENDS DB",81,"Shotgun"],
    ["E-GUN",87,"Shotgun"],
    ["AA-12",112,"Shotgun"],
    ["SPAS-12",120,"Shotgun"],
    ["DT11",133,"Shotgun"],
    ["USAS-12",189,"Shotgun"],
    //PDW
    ["MP5K",0,"PDW"],
    ["UMP45",5,"PDW"],
    ["G36C",7,"PDW"],
    ["MP7",9,"PDW"],
    ["MAC10",23,"PDW"],
    ["P90",24,"PDW"],
    ["COLT MARS",36,"PDW"],
    ["MP5",40,"PDW"],
    ["COLT SMG 633",49,"PDW"],
    ["L2A3",53,"PDW"],
    ["MP5SD",60,"PDW"],
    ["MP10",66,"PDW"],
    ["M3A1",71,"PDW"],
    ["MP5/10",74,"PDW"],
    ["UZI",77,"PDW"],
    ["AUG A3 PARA XS",80,"PDW"],
    ["K7",84,"PDW"],
    ["AKS74U",88,"PDW"],
    ["PPSH-41",92,"PDW"],
    ["FAL PARA SHORTY",92,"PDW"],
    ["KRISS VECTOR",100,"PDW"],
    ["PP-19 BIZON",105,"PDW"],
    ["MP40",108,"PDW"],
    ["X95 SMG",115,"PDW"],
    ["TOMMY GUN",121,"PDW"],
    ["RAMA 1130",126,"PDW"],
    ["BWC9 A",149,"PDW"],
    ["FIVE-0",155,"PDW"],
    //DMRs
    ["MK11",3,"DMR"],
    ["SKS",13,"DMR"],
    ["SL-8",34,"DMR"],
    ["VSS VINTOREZ",46,"DMR"],
    ["MSG90",59,"DMR"],
    ["M21",68,"DMR"],
    ["BEOWULF TCR",70,"DMR"],
    ["SA58 SPR",78,"DMR"],
    ["SCAR SSR",85,"DMR"],
    //LMGs
    ["COLT LMG",0,"LMG"],
    ["M60",19,"LMG"],
    ["AUG HBAR",27,"LMG"],
    ["MG36",33,"LMG"],
    ["RPK12",37,"LMG"],
    ["L86 LSW",43,"LMG"],
    ["RPK",54,"LMG"],
    ["HK21E",67,"LMG"],
    ["HAMR IAR",72,"LMG"],
    ["RPK74",88,"LMG"],
    ["MG3KWS",101,"LMG"],
    ["MGV-176",176,"LMG"],
    ["STONER 96",196,"LMG"],
    ["MG42",242,"LMG"],
    //Sniper rifles
    ["INTERVENTION",0,"Sniper Rifle"],
    ["MODEL 700",12,"Sniper Rifle"],
    ["DRAGUNOV SVU",38,"Sniper Rifle"],
    ["AWS",41,"Sniper Rifle"],
    ["BFG 50",65,"Sniper Rifle"],
    ["AWM",82,"Sniper Rifle"],
    ["TRG-42",82,"Sniper Rifle"],
    ["MOSIN NAGANT",91,"Sniper Rifle"],
    ["DRAGUNOV SVDS",104,"Sniper Rifle"],
    ["M1903",136,"Sniper Rifle"],
    ["K14",138,"Sniper Rifle"],
    ["HECATE II",150,"Sniper Rifle"],
    ["FT300",160,"Sniper Rifle"],
    ["M107",170,"Sniper Rifle"],
    ["STERY SCOUT",195,"Sniper Rifle"],
    ["WA2000",200,"Sniper Rifle"],
    ["NTW-20",220,"Sniper Rifle"]
]
const Secondaries=[
    //Pistols
    ["G17",0,"Pistol"],
    ["M9",0,"Pistol"],
    ["M1911A1",8,"Pistol"],
    ["DESERT EAGLE L5",18,"Pistol"],
    ["G21",21,"Pistol"],
    ["G23",23,"Pistol"],
    ["M45A1",34,"Pistol"],
    ["G40",40,"Pistol"],
    ["KG-99",50,"Pistol"],
    ["G50",50,"Pistol"],
    ["FIVE SEVEN",57,"Pistol"],
    ["ZIP 22",61,"Pistol"],
    ["GI M1",73,"Pistol"],
    ["HARDBALLER",84,"Pistol"],
    ["IZHEVSK PB",91,"Pistol"],
    ["MAKAROV PM",92,"Pistol"],
    ["GB-22",99,"Pistol"],
    ["DESERT EAGLE XIX",102,"Pistol"],
    ["AUTOMAG III",109,"Pistol"],
    ["GYROJET MARK I",122,"Pistol"],
    ["GSP",131,"Pistol"],
    ["GRIZZLY",143,"Pistol"],
    ["M2011",146,"Pistol"],
    ["ALIEN",179,"Pistol"],
    ["AF2011-A1",201,"Pistol"],
    //Machine Pistols
    ["G18C",17,"Machine Pistol"],
    ["93R",26,"Machine Pistol"],
    ["PP-2000",42,"Machine Pistol"],
    ["TEC-9",50,"Machine Pistol"],
    ["MICRO UZI",68,"Machine Pistol"],
    ["ŠKORPION VZ.61",87,"Machine Pistol"],
    ["ASMI",97,"Machine Pistol"],
    ["MP1911",106,"Machine Pistol"],
    ["ARM PISTOL",106,"Machine Pistol"],
    //Revolvers
    ["MP412 REX",4,"Revolver"],
    ["MATEBA 6",29,"Revolver"],
    ["1858 NEW ARMY",58,"Revolver"],
    ["REDHAWK 44",83,"Revolver"],
    ["JUDGE",113,"Revolver"],
    ["EXECUTIONER",137,"Revolver"],
    //Other
    ["SUPER SHORTY",36,"Other"],
    ["SFG 50",75,"Other"],
    ["M79 THUMPER",79,"Other"],
    ["ADVANCED COILGUN",87,"Other"],
    ["SAWED OFF",90,"Other"],
    ["SAIGA-12U",95,"Other"],
    ["OBREZ",117,"Other"],
    ["SASS 308",132,"Other"]
]
//Melees
const Melees=[
    //One hand blades
    ["CLEAVER","One hand blade"],
    ["KARAMBIT","One hand blade"],
    ["KRAMPUS KUKRI","One hand blade"],
    ["WAR FAN","One hand blade"],
    ["NATA HATCHET","One hand blade"],
    ["TANZINATE BLADE","One hand blade"],
    ["KUNAI","One hand blade"],
    ["TACTICAL SPATULA","One hand blade"],
    ["MEK'LETH","One hand blade"],
    ["TANTO","One hand blade"],
    ["HUNTING KNIFE","One hand blade"],
    ["KNIFE","One hand blade"],
    ["TRENCH KNIFE","One hand blade"],
    ["GOSPELL BLADE","One hand blade"],
    ["ENTRENCHER","One hand blade"],
    ["RITUAL SICKLE","One hand blade"],
    ["KAMA","One hand blade"],
    ["KEY","One hand blade"],
    ["ICE PICK","One hand blade"],
    ["MACHETE","One hand blade"],
    ["TOMAHAWK","One hand blade"],
    ["POCKET KNIFE","One hand blade"],
    ["HAVOC BLADE","One hand blade"],
    ["CUTTER","One hand blade"],
    ["JASON","One hand blade"],
    ["BRIDAL BRANDISHER","One hand blade"],
    ["DARKHEART","One hand blade"],
    ["STREITER","One hand blade"],
    ["BALISONG","One hand blade"],
    ["KOMMANDO","One hand blade"],
    ["LINKED SWORD","One hand blade"],
    ["CLASSIC KNIFE","One hand blade"],
    ["HRUNTING","One hand blade"],
    //Two hand blades
    ["ZIRCON TRIDENT","Two hand blade"],
    ["NORDIC WAR AXE","Two hand blade"],
    ["ICEMOURNE","Two hand blade"],
    ["WORLD BUSTER","Two hand blade"],
    ["NOOBSLAYER","Two hand blade"],
    ["HATTORI","Two hand blade"],
    ["CHOSEN ONE","Two hand blade"],
    ["REAPER","Two hand blade"],
    ["ZERO CUTTER","Two hand blade"],
    ["NAGINATA","Two hand blade"],
    ["TRAINING BAYONET","Two hand blade"],
    ["LONGSWORD","Two hand blade"],
    ["FIREAXE","Two hand blade"],
    ["HARVESTER","Two hand blade"],
    ["ZWEIHANDER","Two hand blade"],
    //One Hand Blunts
    ["ASP BATON","One hand blunt"],
    ["TOY GUN","One hand blunt"],
    ["MAGLITE CLUB","One hand blunt"],
    ["CROWBAR","One hand blunt"],
    ["MJOLNIR","One hand blunt"],
    ["KEYBOARD","One hand blunt"],
    ["FLAME OF OLYMPIA","One hand blunt"],
    ["PACIFIC FM","One hand blunt"],
    ["FUMELEE","One hand blunt"],
    ["CANDY CANE","One hand blunt"],
    ["BARE FISTS","One hand blunt"],
    ["TANZANITE PICK","One hand blunt"],
    ["STICK GRENADE","One hand blunt"],
    ["BLOXY","One hand blunt"],
    ["HOLIDAY TEA","One hand blunt"],
    ["TRENCH MACE","One hand blunt"],
    ["CLONKER","One hand blunt"],
    ["NIGHTSTICK","One hand blunt"],
    ["STUN GUN","One hand blunt"],
    ["UCHIWA","One hand blunt"],
    ["FIXER","One hand blunt"],
    ["BRASS KNUCKLES","One hand blunt"],
    ["CRICKET BAT","One hand blunt"],
    ["FRYING PAN","One hand blunt"],
    ["ARM CANNON","One hand blunt"],
    ["STARLIS FUNPOST","One hand blunt"],
    ["THE COUNTDOWN","One hand blunt"],
    //Two hand blunts
    ["SLEDGE HAMMER","Two hand blunt"],
    ["ZIRCON SLAMSICKLE","Two hand blunt"],
    ["WARHAMMER","Two hand blunt"],
    ["HOCKEY STICK","Two hand blunt"],
    ["SWEEPER","Two hand blunt"],
    ["BASEBALL BAT","Two hand blunt"],
    ["PADDLE","Two hand blunt"],
    ["CURSED SHINAI","Two hand blunt"],
    ["BANJO","Two hand blunt"],
    ["STYLIS BRUSH","Two hand blunt"],
    ["KANABO","Two hand blunt"],
    ["STOPPER","Two hand blunt"],
    ["THE AXE","Two hand blunt"],
    ["VOID STAFF","Two hand blunt"],
    ["MORNING STAR","Two hand blunt"],
]
//Grenades
const Grenades=[
    ["M67 FRAG",0,"Fragmentation"],
    ["MK 2 FRAG",2,"Fragmentation"],
    ["M24 STICK",2,"Fragmentation"],
    ["M26 FRAG",26,"Fragmentation"],
    ["M560 MINI",56,"Fragmentation"],
    ["V40 MINI",140,"Fragmentation"],
    ["ROLY HG",300,"Fragmentation"],
    ["DYNAMITE-3",0,"High explosive"],
    ["DYNAMITE",0,"High explosive"],
    ["RGD-5 HE",54,"High explosive"],
    ["SEMTEX",69,"High explosive"],
    ["PB GRENADE",135,"High explosive"],
    ["BUNDLE CHARGE",168,"High explosive"],
    ["T-13 IMPACT",80,"Impact"],
    ["RGN UDZS",80,"Impact"],
    ["RGO UDZS",114,"Impact"]
]
export {Primaries,Secondaries,Melees,Grenades};